version: '3.7'
volumes:
  pg-data:

services:
  web:
    build:
      context: .
    volumes:
      - ./:/workdir/
    command: "python3 src/run_web.py"
    restart: always
    ports:
      - "6699:6699"